table 'Employee check'
	lineageTag: f3f3934f-1a1a-4af4-a16e-9c5696a450f5

	measure 'Current first name' = "Welcome "& calculate (max('Employee check'[First name]),'Employee check'[Login]=USERPRINCIPALNAME())& " !"
		lineageTag: 0fb81aa0-b273-4a0e-9ec1-50759de9dd1b

		changedProperty = IsHidden

	column 'First name'
		dataType: string
		lineageTag: eee8678b-7ea7-4ca8-a991-65cc4fe62a70
		summarizeBy: none
		sourceColumn: First name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: d868408e-7195-465c-8ed4-104f7e23c183
		summarizeBy: none
		sourceColumn: Login

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Employee check-6bd7d49f-d5c3-4337-aa7f-b2432267b8a5' = m
		mode: import
		queryGroup: 'DIM Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_ONCE, [HierarchicalNavigation=true, Query="select WINDOW_LOGIN, FIRST_NAME from HRR_DM.V_DIM_PERSON_LIGHT"]),
				    #"Capitalized Each Word" = Table.TransformColumns(Source,{{"FIRST_NAME", Text.Proper, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Capitalized Each Word",{{"WINDOW_LOGIN", "Login"}, {"FIRST_NAME", "First name"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [Login] <> null and [Login] <> ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.StartsWith([Login], "NA")),
				    #"Inserted Merged Column" = Table.AddColumn(#"Filtered Rows1", "Merged", each Text.Combine({[Login], "@bpost.be"}), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Merged Column",{"Login"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Merged", "Login"}})
				in
				    #"Renamed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

