table OPTIMAX_EOY_ORG
	lineageTag: 591054f2-6155-4976-8bf4-88adbdcbfdce

	measure '#EOY Count MO+115' = CALCULATE(DISTINCTCOUNT(FACT_HR_OFFICE_DAILY[POSTAL_CODE]), FACT_HR_OFFICE_DAILY[PRIME_CALCULATION] = 4) +0
		formatString: 0
		lineageTag: ef714c10-4817-4414-9a27-403e6158c2bb

	measure '#EOY Count MO+125' = CALCULATE(DISTINCTCOUNT(FACT_HR_OFFICE_DAILY[POSTAL_CODE]), FACT_HR_OFFICE_DAILY[PRIME_CALCULATION] = 6) + 0
		formatString: 0
		lineageTag: 6678b015-69f0-4852-8798-3d5138a56c50

	measure '#EOY Count MO0' = CALCULATE(DISTINCTCOUNT(FACT_HR_OFFICE_DAILY[POSTAL_CODE]), FACT_HR_OFFICE_DAILY[PRIME_CALCULATION] = 0)
		formatString: 0
		lineageTag: a3ef2d15-6229-4c5e-ae00-fb3ec7ee9d81

	measure '#EOY % MO+115' = CALCULATE( OPTIMAX_EOY_ORG[#EOY Count MO+115] / DISTINCTCOUNT(FACT_HR_OFFICE_DAILY[POSTAL_CODE]) )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9b0d70cf-410e-4fa4-be24-c673f41216c3

	measure '#EOY % MO+125' = CALCULATE( OPTIMAX_EOY_ORG[#EOY Count MO+125] / DISTINCTCOUNT(FACT_HR_OFFICE_DAILY[POSTAL_CODE]) )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8d2fcffd-25af-4c2f-ade7-466790039e32

	measure '#EOY % MO0' = CALCULATE( OPTIMAX_EOY_ORG[#EOY Count MO0] / DISTINCTCOUNT(FACT_HR_OFFICE_DAILY[POSTAL_CODE]) ) +0
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c425d821-e6d7-4c91-bf7d-e00ba4034365

	measure '#EOY Count MO Total Prime' = CALCULATE( OPTIMAX_EOY_ORG[#EOY Count MO+115] + OPTIMAX_EOY_ORG[#EOY Count MO+125])
		formatString: 0
		lineageTag: f4e3b973-e4db-4054-b460-ad5a07f3a832

	measure '#EOY % MO Total Prime' = CALCULATE( OPTIMAX_EOY_ORG[#EOY Count MO Total Prime] / DISTINCTCOUNT(FACT_HR_OFFICE_DAILY[POSTAL_CODE]) )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 913030e4-27a4-4f32-b76f-7b557dfc32c3

	measure '#EOY Avg PAK/FTE' = CALCULATE(SUM(FACT_HR_OFFICE_DAILY[AVERAGE_WK_REEL_PARCELS]) / SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_TOTAL]))
		formatString: #,0
		lineageTag: ce9ada5b-878a-48e9-81fb-fd5cd2fed35e

	measure '#EOY % FTE_4' = CALCULATE( SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_PRIME4] ) / SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_TOTAL]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f0d25cf7-307a-4cef-ada5-b0efc61cb819

	measure '#EOY % FTE_6' = CALCULATE( SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_PRIME6] ) / SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_TOTAL]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c2dd1fb2-ff2a-4cca-8001-0e3e299c7eda

	measure '#EOY % FTE_TOTAL' = CALCULATE(SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_PRIME4]) + CALCULATE(SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_PRIME6]))) / SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_TOTAL])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ca45718e-0c60-445e-b663-68b80de20169

	measure '#EOY Avg PAK/FTE DIS' = CALCULATE(SUM(FACT_HR_OFFICE_DAILY[AVERAGE_WK_REEL_PARCELS]) / SUM(FACT_HR_OFFICE_DAILY[NB_ACTUALS_TOTAL_DIS]))
		formatString: #,0
		lineageTag: 0d9cf6a9-7939-416d-9ddd-e996cf2c0566

	measure '#EOY 125 Yes' = SWITCH(TRUE(),SUM(FACT_HR_OFFICE_DAILY[PRIME_CALCULATION]) = 6, "Yes","No")
		lineageTag: ea1dd0af-9d5a-4ede-9f79-2161146beed2

	measure '#EOY 115 Yes' = SWITCH(TRUE(),SUM(FACT_HR_OFFICE_DAILY[PRIME_CALCULATION]) = 4, "Yes","No")
		lineageTag: 1cf8975f-931b-40d3-9155-c6ef0e6b46a7

	measure '#EOY ALL 125/115/0' = SWITCH(TRUE(),[#Avg_PAK_EOY % Delta] > 1.149 && [#Avg_PAK_EOY % Delta] < 1.249 ,"20 Min / 115% ", [#Avg_PAK_EOY % Delta]>=1.249, "30 Min / 125% ","0")
		lineageTag: 721c878d-1397-4d9b-b7a2-340f396bd11c

	column BUREAU_PHYSIQUE
		dataType: string
		lineageTag: 351adced-3813-48ab-8188-6d5778d29bf6
		summarizeBy: none
		sourceColumn: BUREAU_PHYSIQUE

		annotation SummarizationSetBy = Automatic

	column NOM_BUREAU
		dataType: string
		lineageTag: 3d83d181-5285-4348-aa26-ab6bf329b766
		summarizeBy: none
		sourceColumn: NOM_BUREAU

		annotation SummarizationSetBy = Automatic

	column CP_GEOROUTE
		dataType: int64
		lineageTag: f4fba192-99d2-4fce-8ed8-20035ccb70f5
		summarizeBy: none
		sourceColumn: CP_GEOROUTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MC
		dataType: string
		lineageTag: af9b7212-d43e-41e4-8006-217dc93c407a
		summarizeBy: none
		sourceColumn: MC

		annotation SummarizationSetBy = Automatic

	column DM
		dataType: string
		lineageTag: 1b66e9c7-218e-4b91-956d-5db377c75e24
		summarizeBy: none
		sourceColumn: DM

		annotation SummarizationSetBy = Automatic

	column COLLECT
		dataType: string
		lineageTag: 35788e39-fb0e-4331-9099-da9be0d83a1f
		summarizeBy: none
		sourceColumn: COLLECT

		annotation SummarizationSetBy = Automatic

	column PARCELS_ORG
		dataType: double
		lineageTag: a684df4b-d153-4036-8a68-dd687db0f01e
		summarizeBy: none
		sourceColumn: PARCELS_ORG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CORRECTION
		dataType: double
		lineageTag: 79d8bb7e-b871-4af4-9d44-1fd3c5c42f84
		summarizeBy: none
		sourceColumn: CORRECTION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EOY_ORG_2023
		dataType: double
		formatString: #,0
		lineageTag: 09c57071-f336-406d-8882-7cb16d55c3c0
		summarizeBy: none
		sourceColumn: EOY_ORG_2023

		annotation SummarizationSetBy = Automatic

	column COMMENT_IF_CORRECTION
		dataType: string
		lineageTag: 4709ba6a-a39c-4cad-bad6-86b6402b8529
		summarizeBy: none
		sourceColumn: COMMENT_IF_CORRECTION

		annotation SummarizationSetBy = Automatic

	column GROWTH
		dataType: double
		lineageTag: a2140ea5-e517-4f43-bf1f-a3440d26a146
		summarizeBy: none
		sourceColumn: GROWTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition OPTIMAX_EOY_ORG = m
		mode: import
		queryGroup: 'DIM Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_SECOND, [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    OPTIMAX_EOY_ORG1 = PBI_VLT341{[Name="OPTIMAX_EOY_ORG"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(OPTIMAX_EOY_ORG1,{{"CP_GEOROUTE", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

