table V_PBI_PAKSAT_TIME
	lineageTag: 8c45b2cc-5815-4a63-8ad1-73ce4767476b

	measure '#Pak_sat Actuals / hours' =
			
			CALCULATE(
				[#Avg_PAK_REEL]/
				[#Pak_sat AVG FTE ACT]/7.6)
		formatString: #,0
		lineageTag: 08dd907f-dae9-4568-8f33-39a62675ccf2

	measure '#Pak_sat Parcels Actuals / FTE' = ```
			
				CALCULATE([#Avg_PAK_REEL]/ [#Pak_sat AVG FTE ACT])
			```
		formatString: #,0.0
		lineageTag: 00023984-e7b4-4206-a607-d845d34ce957

	measure '#Pak_sat AVG FTE ACT' = CALCULATE(SUM(V_PBI_PAKSAT_TIME[FTE_ACT_PAKSAT]) / DISTINCTCOUNT(V_PBI_PAKSAT_TIME[DATE_YYYYMMDD]))
		formatString: #,0.0
		lineageTag: 15b9d31f-0ccd-41c0-a4de-2bbf2519b29e

	measure '#Pak_sat AVG FTE ORG' = CALCULATE(SUM(V_PBI_PAKSAT_TIME[FTE_PAKSAT_ORG]) / DISTINCTCOUNT(V_PBI_PAKSAT_TIME[DATE_YYYYMMDD]))
		formatString: #,0.0
		lineageTag: 8d0a4d1f-8620-4096-9f56-71b58af9eaaf

	measure '#Pak_sat Variation FTE %' =
			
			VAR __BASELINE_VALUE = [#Pak_sat AVG FTE ORG]
			VAR __VALUE_TO_COMPARE = [#Pak_sat AVG FTE ACT]
			RETURN
				IF(
					NOT ISBLANK(__VALUE_TO_COMPARE),
					DIVIDE(__VALUE_TO_COMPARE - __BASELINE_VALUE, __BASELINE_VALUE)
				)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2f52136f-7784-4120-a24e-b8c29ba8a87e

	measure '#Pak_sat ORG Parcels' = CALCULATE(SUM(V_PBI_PAKSAT_TIME[PARCELS_ORG]) / DISTINCTCOUNT(V_PBI_PAKSAT_TIME[DATE_YYYYMMDD]))
		formatString: #,0
		lineageTag: deb74550-46e6-4a04-94ae-3e207b223c53

	measure '#Pak_Sat Avg_Pak % delta' =
			
			VAR __BASELINE_VALUE = [#Pak_sat ORG Parcels]
			VAR __VALUE_TO_COMPARE = [#Avg_PAK_REEL]
			RETURN
				IF(
					NOT ISBLANK(__VALUE_TO_COMPARE),
					DIVIDE(__VALUE_TO_COMPARE , __BASELINE_VALUE)
				) -1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 52b04fb9-71ad-4ed4-abee-956f9d7a17c4

	measure '#Pak_sat ORG NPP' = CALCULATE(SUM(V_PBI_PAKSAT_TIME[NPP_SAT_ORG]) / DISTINCTCOUNT(V_PBI_PAKSAT_TIME[DATE_YYYYMMDD]))
		formatString: 0
		lineageTag: 4379cd34-be11-4cbf-a7e8-88fae893cde8

	measure '#Pak_Sat Avg_NPP % delta' =
			
			VAR __BASELINE_VALUE = [#Pak_sat ORG NPP]
			VAR __VALUE_TO_COMPARE = [#Avg_KRANTEN_REEL]
			RETURN
				IF(
					NOT ISBLANK(__VALUE_TO_COMPARE),
					DIVIDE(__VALUE_TO_COMPARE , __BASELINE_VALUE)
				) -1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 42280a9e-8dec-437a-b3e7-3a3f3d0a78b3

	column DATE_YYYYMMDD
		dataType: double
		lineageTag: 98fc2b9a-b8c4-4a8a-8445-8e978371740f
		summarizeBy: none
		sourceColumn: DATE_YYYYMMDD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CADRE_DISTRI_SAT
		dataType: double
		lineageTag: 39cd3c64-d7d8-4d5c-8fcc-8b5e1abd73d3
		summarizeBy: none
		sourceColumn: CADRE_DISTRI_SAT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FTE_PAKSAT_ORG
		dataType: double
		lineageTag: 8e5c71a5-a181-414b-92e7-501bf0eb58e7
		summarizeBy: none
		sourceColumn: FTE_PAKSAT_ORG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ASSURED_DURATION_PLA
		dataType: double
		lineageTag: 48ca9508-eac5-4e69-8aca-f508a56481d7
		summarizeBy: none
		sourceColumn: ASSURED_DURATION_PLA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CADRE_SAT_OTHER
		dataType: double
		lineageTag: c3a1f622-0c86-49fc-aac1-4812eb12f191
		summarizeBy: none
		sourceColumn: CADRE_SAT_OTHER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FTE_ACT_PAKSAT
		dataType: double
		lineageTag: 7732028e-f610-48a7-b57e-c3f1e8de491e
		summarizeBy: none
		sourceColumn: FTE_ACT_PAKSAT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KEY_PS
		dataType: string
		lineageTag: 7fd546e4-a159-43b3-ae15-b9ea609f996b
		summarizeBy: none
		sourceColumn: KEY_PS

		annotation SummarizationSetBy = Automatic

	column MIN_PER_PARCELS_ORG
		dataType: double
		lineageTag: a3181512-1259-45bb-baba-64199555e406
		summarizeBy: none
		sourceColumn: MIN_PER_PARCELS_ORG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MIN_PER_PARCELS_ACTUALS
		dataType: double
		lineageTag: dbde6229-d6ba-40f9-aed2-30b9085e5d3f
		summarizeBy: none
		sourceColumn: MIN_PER_PARCELS_ACTUALS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PARCELS_ORG
		dataType: double
		lineageTag: 7756b3a0-a3a8-4e9e-9cb0-70fa5bc6c5e2
		summarizeBy: none
		sourceColumn: PARCELS_ORG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NPP_SAT_ORG
		dataType: double
		lineageTag: 72e381ff-7792-4b35-9c9f-967e20870e68
		summarizeBy: none
		sourceColumn: NPP_SAT_ORG

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition V_PBI_PAKSAT_TIME-12fc928b-ea1f-46b2-b490-115562bda5a9 = m
		mode: import
		queryGroup: 'DIM Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_ONCE, [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    V_PBI_PAKSAT_TIME1 = PBI_VLT341{[Name="OPTIMAX_PAKSAT_TIME"]}[Data]
				in
				    V_PBI_PAKSAT_TIME1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

