table OPTIMAX_TBL_EOY_2023_MAPPING
	lineageTag: 31b20d7d-18b2-4cdf-a1f5-ccf0a5dff3bb

	column DEPT_CD
		dataType: int64
		formatString: 0
		lineageTag: d8b19668-f38a-4704-a9e7-400f3965340f
		summarizeBy: none
		sourceColumn: DEPT_CD

		annotation SummarizationSetBy = Automatic

	column DEPT_DESC
		dataType: string
		lineageTag: 9c50c0a8-7e44-4fd0-b0b9-0089bf8f31e2
		summarizeBy: none
		sourceColumn: DEPT_DESC

		annotation SummarizationSetBy = Automatic

	column MO_NAME
		dataType: string
		lineageTag: 8a5a054f-3c7e-4b64-99ca-58db6c260a16
		summarizeBy: none
		sourceColumn: MO_NAME

		annotation SummarizationSetBy = Automatic

	column MC_NAME
		dataType: string
		lineageTag: c7b101e9-a4c0-465f-96f7-0fcf37cce7f6
		summarizeBy: none
		sourceColumn: MC_NAME

		annotation SummarizationSetBy = Automatic

	column POSTAL_CODE
		dataType: int64
		formatString: 0
		lineageTag: 21361738-9e22-4389-b6f6-75adb6fb30f5
		summarizeBy: none
		sourceColumn: POSTAL_CODE

		annotation SummarizationSetBy = Automatic

	column MO_CODE
		dataType: int64
		lineageTag: ba62d047-4a5d-4a73-8ce0-4377188f3268
		summarizeBy: none
		sourceColumn: MO_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition OPTIMAX_TBL_EOY_2023_MAPPING = m
		mode: import
		queryGroup: 'DIM Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_SECOND, [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    OPTIMAX_TBL_EOY_2023_MAPPING1 = PBI_VLT341{[Name="OPTIMAX_TBL_EOY_2023_MAPPING"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(OPTIMAX_TBL_EOY_2023_MAPPING1,{{"POSTAL_CODE", Int64.Type}, {"DEPT_CD", Int64.Type}, {"MO_CODE", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

