table 'Employee check'
	lineageTag: 83c6c0bb-b704-4e67-8c88-e53276a1e8c5

	column 'First name'
		dataType: string
		lineageTag: a0671b6b-0360-4c53-9308-610f8610054f
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: 14ee7055-0d5a-4505-a803-6ece577d3cc5
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	partition 'Employee check' = m
		mode: import
		queryGroup: 'DIM Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_ONCE, [HierarchicalNavigation=true, Query="select WINDOW_LOGIN, FIRST_NAME from HRR_DM.V_DIM_PERSON_LIGHT", CommandTimeout=#duration(0, 1, 30, 0)]),
				    #"Capitalized Each Word" = Table.TransformColumns(Source,{{"FIRST_NAME", Text.Proper, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Capitalized Each Word",{{"WINDOW_LOGIN", "Login"}, {"FIRST_NAME", "First name"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [Login] <> null and [Login] <> ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.StartsWith([Login], "NA")),
				    #"Inserted Merged Column" = Table.AddColumn(#"Filtered Rows1", "Merged", each Text.Combine({[Login], "@bpost.be"}), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Merged Column",{"Login"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Merged", "Login"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

