table DIM_CALENDAR
	lineageTag: ceed0860-b0eb-4270-a07d-828169766f39

	measure 'Target value 6' = 6
		formatString: 0
		lineageTag: 63bb0ce6-2ec1-449e-a741-40886e344327

	column PIC_KEY
		dataType: string
		lineageTag: c3e7a205-c99d-4280-9a96-26219affdf65
		summarizeBy: none
		sourceColumn: PIC_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter = CONCATENATE("Quarter ",'DIM_CALENDAR'[Quarter_])
		lineageTag: 08b33350-b848-4eb6-b61b-4b759990ecb4
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month_ = CONCATENATE(CONCATENATE(IF(LEN('DIM_CALENDAR'[Month Number])=1,CONCATENATE("0",'DIM_CALENDAR'[Month Number]),'DIM_CALENDAR'[Month Number])," - "),CONCATENATE('DIM_CALENDAR'[Month Name]," "))
		lineageTag: 688e498b-b208-4082-8866-a5bbceedb538
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Week = DIM_CALENDAR[Year] & "-" & CONCATENATE("Week ",IF(LEN('DIM_CALENDAR'[Week Number ISO])=1,CONCATENATE("0",'DIM_CALENDAR'[Week Number ISO]),'DIM_CALENDAR'[Week Number ISO]))
		lineageTag: 4bb212fe-99cb-455f-9bc5-9e348584b3a0
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Date tooltip'
		dataType: string
		lineageTag: 72e91d06-b0c0-4830-a94c-7cbdcff9e7ba
		summarizeBy: none
		sourceColumn: Date tooltip

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstDayOfCurrentYear = MIN(V_PBI_DIM_REORG_VLT[REORG START dateFormatted])
		dataType: dateTime
		formatString: Short Date
		lineageTag: 685a89d5-f37b-4693-a526-08360d7d87cc
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e48c15ab-6dd7-48c4-8c00-c8ea7669c667
			defaultHierarchy: LocalDateTable_eb01b47e-4241-4ab2-b34b-e714aec3cf82.'Hiérarchie de dates'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsInRange = IF('DIM_CALENDAR'[Date Range] >= 'DIM_CALENDAR'[FirstDayOfCurrentYear] && 'DIM_CALENDAR'[Date Range] <= TODAY(), TRUE(), FALSE())
		lineageTag: 779be756-15e3-4a26-964d-d5ffec26efa9
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 9d490770-9548-41b3-adb9-bca6b78753f5
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day Number'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Date Range'
		dataType: dateTime
		lineageTag: adca96b2-bfae-4d45-a824-c03a704f733e
		summarizeBy: none
		sourceColumn: Date Range
		sortByColumn: 'Date YYYYMMDD'

		variation Variation
			isDefault
			relationship: 86f06861-5350-458a-8b4e-85ecd1f4e854
			defaultHierarchy: LocalDateTable_9a7e7e85-6aa2-4baa-a2fa-3244a1340826.'Hiérarchie de dates'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Date YYYYMMDD'
		dataType: int64
		lineageTag: 9208d4f7-c370-4749-a755-e6fc7eca6dc0
		summarizeBy: none
		sourceColumn: Date YYYYMMDD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Number'
		dataType: int64
		lineageTag: 176a9ad1-f067-4205-b7c7-74d19b6e5d8f
		summarizeBy: sum
		sourceColumn: Day Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		lineageTag: e120e7e7-0250-4d3a-b461-96ee91376bf2
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Number'
		dataType: int64
		lineageTag: 2a43e410-2903-44f6-8731-f378bfdfc590
		summarizeBy: sum
		sourceColumn: Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: int64
		lineageTag: a72af52e-2b4b-40bb-a993-d146c795c803
		summarizeBy: sum
		sourceColumn: Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: int64
		lineageTag: 14046545-c824-42be-8c00-c946b006fbb9
		summarizeBy: sum
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quarter_
		dataType: int64
		lineageTag: a840776d-bc1b-4a9d-859c-fc23192eda45
		summarizeBy: sum
		sourceColumn: Quarter_

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Name EN'
		dataType: string
		lineageTag: 9aa50c8e-0f4a-4081-97f9-9c80e4f30a5f
		summarizeBy: none
		sourceColumn: Day Name EN
		sortByColumn: 'Day Number'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: c3b7998a-5d50-4050-b95f-f15db34a5e81
		summarizeBy: none
		sourceColumn: Month Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Legal Holiday'
		dataType: string
		lineageTag: fcc8b33d-2890-4dab-b29b-f07370ee785d
		summarizeBy: none
		sourceColumn: Legal Holiday

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Work Day'
		dataType: string
		lineageTag: 89b604b3-1313-4226-984e-fef0333cd6c9
		summarizeBy: none
		sourceColumn: Work Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Week Number ISO'
		dataType: int64
		lineageTag: a4122ef7-3c31-4489-92c1-13907e4bd259
		summarizeBy: sum
		sourceColumn: Week Number ISO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Year' = ```
			FORMAT([Date Range],"mmm-yyyy") 
			```
		lineageTag: 8c65e76a-2954-40f3-a76f-a0bdd15b8c92
		summarizeBy: none
		sortByColumn: 'Month Year sort'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Year sort' = FORMAT([Date Range],"yyyymm")
		lineageTag: cd3087d4-f701-410c-960c-d94801b3407e
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Week sort' = DIM_CALENDAR[Month Year sort]& DIM_CALENDAR[Week Number ISO]
		lineageTag: 080c30fd-b9eb-413f-87d2-d87d3b0dc6f3
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Covid = IF(DIM_CALENDAR[Month Year] = "mars-2020", "COVID",BLANK())
		lineageTag: fda9c182-4b61-4d14-ad99-f44d55e7b625
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Info' = CONCATENATE(CONCATENATE(DIM_CALENDAR[Month Year], "   " ),DIM_CALENDAR[Covid])
		lineageTag: 7b9300ad-76b1-40f7-87da-97c4e114f4c8
		summarizeBy: none
		sortByColumn: 'Month Year sort'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WEEK_NUMBER_YYYYWWW_ISO
		dataType: string
		lineageTag: 8bcce2e4-0c0c-49dc-a8e7-55b4b7b50994
		summarizeBy: none
		sourceColumn: WEEK_NUMBER_YYYYWWW_ISO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ADAPTED_SERVICE_HOLIDAY
		dataType: string
		lineageTag: ea9b214c-1e49-47b9-9b88-81373157dd06
		summarizeBy: none
		sourceColumn: ADAPTED_SERVICE_HOLIDAY

		annotation SummarizationSetBy = Automatic

	column WEEKEND_EOY
		dataType: string
		lineageTag: df81ba65-9537-4499-a48f-d72efbc9a99a
		summarizeBy: none
		sourceColumn: WEEKEND_EOY

		annotation SummarizationSetBy = Automatic

	column 'IsInRanges WORKLOAD' = IF('DIM_CALENDAR'[Date YYYYMMDD] <= [Max Date DATA] ,TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 822bc62b-7060-4c5d-a4de-d066a2b8fd16
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Year Hierarchy - INFO'
		lineageTag: 73a9029c-7b72-4efc-a577-5020e2cd559b

		level Year
			lineageTag: 786cbc6c-ff3a-4330-a5dc-f4615852b41a
			column: Year

		level 'Month Info'
			lineageTag: f9ef2e7f-ba3a-4e54-968f-93381239e951
			column: 'Month Info'

		changedProperty = IsHidden

	hierarchy 'Year Hierarchy'
		lineageTag: e13dc6fb-22c6-47e9-9370-2c913cf573cb

		level Year
			lineageTag: 8d85b2a4-dc9c-42d0-bb16-a5071bce8d95
			column: Year

		level 'Month Year'
			lineageTag: e4ce2006-dc1b-4e59-ab07-e47e38f36226
			column: 'Month Year'

		level Week
			lineageTag: 0c01753e-a662-43ac-8bb1-689e43249b94
			column: Week

		level 'Date Range'
			lineageTag: 7ab252df-0cdb-40be-81d7-c6412f456cb2
			column: 'Date Range'

		changedProperty = IsHidden

	partition DIM_CALENDAR-7dcf9b38-ccc5-42fc-bc4b-ed7c205591c9 = m
		mode: import
		queryGroup: 'DIM Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT_CO8P1, [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    V_PBI_DIM_CALENDAR1 = PBI_VLT341{[Name="OPTIMAX_DIM_CALENDAR"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(V_PBI_DIM_CALENDAR1,{{"Week Number ISO", Int64.Type}, {"Quarter_", Int64.Type}, {"Month", Int64.Type}, {"Day", Int64.Type}, {"Month Number", Int64.Type}, {"Date YYYYMMDD", Int64.Type}, {"Day Number", Int64.Type}, {"Year", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

