table 'Employee check'
	lineageTag: cf2c4468-ad22-4cb8-bc83-39edfb17c676

	measure 'Current first name' = "Welcome "& calculate (max('Employee check'[First name]),'Employee check'[Login]=USERPRINCIPALNAME())& " !"
		lineageTag: 9805d1ea-37c9-4f46-8c57-310274da9c08

	column 'First name'
		dataType: string
		lineageTag: a816ce1a-c384-439b-a7fe-2ea6ae77e271
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: b7e8961f-7199-4a2f-83ac-082323984010
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	partition 'Employee check' = m
		mode: import
		queryGroup: 'FACT Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT_CO8P1, [HierarchicalNavigation=true, Query="select WINDOW_LOGIN, FIRST_NAME from HRR_DM.V_DIM_PERSON_LIGHT"]),
				    #"Capitalized Each Word" = Table.TransformColumns(Source,{{"FIRST_NAME", Text.Proper, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Capitalized Each Word",{{"WINDOW_LOGIN", "Login"}, {"FIRST_NAME", "First name"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [Login] <> null and [Login] <> ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.StartsWith([Login], "NA")),
				    #"Inserted Merged Column" = Table.AddColumn(#"Filtered Rows1", "Merged", each Text.Combine({[Login], "@bpost.be"}), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Merged Column",{"Login"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Merged", "Login"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

