table 'Employee check'
	lineageTag: c4bbe975-e413-4b00-8bff-729784ebbec8

	measure 'Current first name' = "Welcome "& calculate (max('Employee check'[First name]),'Employee check'[Login]=USERPRINCIPALNAME())& " !"
		lineageTag: 4287d04f-6bf4-4549-929d-c86a5d51c82c

	column 'First name'
		dataType: string
		lineageTag: 7c40f226-8dde-43e7-a359-74b4babe6cd2
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column Login
		dataType: string
		lineageTag: 9569be26-69d3-4086-a11c-f3f843904e85
		summarizeBy: none
		sourceColumn: Login

		annotation SummarizationSetBy = Automatic

	partition 'Employee check-68e6ee17-554c-4ad3-b44b-8492fcbd0b72' = m
		mode: import
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_ONCE, [HierarchicalNavigation=true, Query="select WINDOW_LOGIN, FIRST_NAME from HRR_DM.V_DIM_PERSON_LIGHT"]),
				    #"Capitalized Each Word" = Table.TransformColumns(Source,{{"FIRST_NAME", Text.Proper, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Capitalized Each Word",{{"WINDOW_LOGIN", "Login"}, {"FIRST_NAME", "First name"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [Login] <> null and [Login] <> ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.StartsWith([Login], "NA")),
				    #"Inserted Merged Column" = Table.AddColumn(#"Filtered Rows1", "Merged", each Text.Combine({[Login], "@bpost.be"}), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Merged Column",{"Login"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Merged", "Login"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

