table DIM_CALENDAR_FUTUR
	lineageTag: ceed0860-b0eb-4270-a07d-828169766f39
	dataCategory: Time

	measure sumarize
		lineageTag: c20f2298-71b0-4135-9c83-03a59971fce4

	measure Measure
		lineageTag: 17e40b87-94e9-4422-94d2-2d1bd2407ffc

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Filter_Both_Zero
		lineageTag: 314b3209-7b91-40fe-b54c-61f2558ec481

	measure '#Delta % Reel / Org' = SUM(DISTRIPOST_TBL_IRN_PLANNED[TOTAL_MAILBOX_VOLUME]) / SUM(DISTRIPOST_IRN_PLANNED_AGG_PBI[ORG_ENA])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 73eee759-e0f7-4dc5-896f-b097afd11829

	measure '#Delta % Reel / Org / Round' = SUM(DISTRIPOST_TBL_IRN_PLANNED[TOTAL_MAILBOX_VOLUME]) / SUM(DISTRIPOST_TBL_IRN_PLANNED[ORG_ENA])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4ef4af32-d7aa-4afa-ba64-e96fe9bbf01a

	measure 'Max Date Past' = MAX(V_PBI_DISTRIPOST[DATE_YYYYMMDD])
		lineageTag: 00b55101-9929-46bc-b5ed-7b8520b5cd61

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAX dateFormatted' = Date(Left([Max Date Past],4),Right(left([Max Date Past],6),2),right([Max Date Past],2))
		formatString: Short Date
		lineageTag: 88cc73b1-064d-4f2d-9db9-3b535a66f9c1

	measure 'Max Date forecast' = MAX(DISTRIPOST_TBL_IRN_PLANNED[REQ_DISTR_END_DATE_YYYYMMDD])
		lineageTag: fcc39126-b138-4b4f-8701-a59e42c19d2f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAX dateFormatted forecast' = Date(Left([Max Date forecast],4),Right(left([Max Date forecast],6),2),right([Max Date forecast],2))
		formatString: Short Date
		lineageTag: 814c76bc-2f7c-451a-9948-3802fd8a2c55

	measure Part_Client_% = ```
			
			DIVIDE(
			    SUM('DISTRIPOST_TBL_IRN_PLANNED'[TOTAL_MAILBOX_VOLUME]),
			    CALCULATE(SUM('DISTRIPOST_TBL_IRN_PLANNED'[TOTAL_MAILBOX_VOLUME]), ALL('DISTRIPOST_TBL_IRN_PLANNED'[CUSTOMER_NAME]))
			) 
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 063dd0fe-fad4-45d6-bcb0-bb5680755b0b

	measure '#Delta % Reel / Org / Tab' = SUM(DISTRIPOST_TBL_IRN_PLANNED[TOTAL_MAILBOX_VOLUME]) / SUM(DISTRIPOST_TBL_IRN_PLANNED[ORG_ENA])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ee2f498a-ce83-4ba0-aaf4-abe3e50463ce

	measure 'MAX DATE PARCELS FORECAST' = MAX(FORECAST_PARCELS[DATE_YYYYMMDD])
		lineageTag: 87f3a051-4e24-44ab-adab-9754844c3a31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAX dateFormatted Parcels Forecast' = Date(Left([MAX DATE PARCELS FORECAST],4),Right(left([MAX DATE PARCELS FORECAST],6),2),right([MAX DATE PARCELS FORECAST],2))
		formatString: dddd\, d mmmm yyyy
		lineageTag: 5a7e7aa8-8775-4295-bae9-e12b2a9aeea4

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column PIC_KEY
		dataType: string
		lineageTag: c3e7a205-c99d-4280-9a96-26219affdf65
		summarizeBy: none
		sourceColumn: PIC_KEY

		annotation SummarizationSetBy = Automatic

	column Quarter = CONCATENATE("Quarter ",'DIM_CALENDAR_FUTUR'[Quarter_])
		lineageTag: 08b33350-b848-4eb6-b61b-4b759990ecb4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Month_ = CONCATENATE(CONCATENATE(IF(LEN('DIM_CALENDAR_FUTUR'[Month Number])=1,CONCATENATE("0",'DIM_CALENDAR_FUTUR'[Month Number]),'DIM_CALENDAR_FUTUR'[Month Number])," - "),CONCATENATE('DIM_CALENDAR_FUTUR'[Month Name]," "))
		lineageTag: 688e498b-b208-4082-8866-a5bbceedb538
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Week = DIM_CALENDAR_FUTUR[Year] & "-" & CONCATENATE("W",IF(LEN('DIM_CALENDAR_FUTUR'[Week Number ISO])=1,CONCATENATE("0",'DIM_CALENDAR_FUTUR'[Week Number ISO]),'DIM_CALENDAR_FUTUR'[Week Number ISO]))
		lineageTag: 4bb212fe-99cb-455f-9bc5-9e348584b3a0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Date tooltip'
		dataType: string
		lineageTag: 72e91d06-b0c0-4830-a94c-7cbdcff9e7ba
		summarizeBy: none
		sourceColumn: Date tooltip

		annotation SummarizationSetBy = Automatic

	column FirstDayOfCurrentYear = MIN(DIM_REORG_VLT[REORG START dateFormatted])
		dataType: dateTime
		formatString: Short Date
		lineageTag: 685a89d5-f37b-4693-a526-08360d7d87cc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsInRange = IF('DIM_CALENDAR_FUTUR'[Date Range] >= 'DIM_CALENDAR_FUTUR'[FirstDayOfCurrentYear] && 'DIM_CALENDAR_FUTUR'[Date Range] <= TODAY(), TRUE(), FALSE())
		lineageTag: 779be756-15e3-4a26-964d-d5ffec26efa9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 9d490770-9548-41b3-adb9-bca6b78753f5
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day Number'

		annotation SummarizationSetBy = Automatic

	column 'Date Range'
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: adca96b2-bfae-4d45-a824-c03a704f733e
		summarizeBy: none
		sourceColumn: Date Range
		sortByColumn: 'Date YYYYMMDD'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Date YYYYMMDD'
		dataType: int64
		lineageTag: 9208d4f7-c370-4749-a755-e6fc7eca6dc0
		summarizeBy: none
		sourceColumn: Date YYYYMMDD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Number'
		dataType: int64
		lineageTag: 176a9ad1-f067-4205-b7c7-74d19b6e5d8f
		summarizeBy: none
		sourceColumn: Day Number

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		lineageTag: e120e7e7-0250-4d3a-b461-96ee91376bf2
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Number'
		dataType: int64
		lineageTag: 2a43e410-2903-44f6-8731-f378bfdfc590
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Day
		dataType: int64
		lineageTag: a72af52e-2b4b-40bb-a993-d146c795c803
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: int64
		lineageTag: 14046545-c824-42be-8c00-c946b006fbb9
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quarter_
		dataType: int64
		lineageTag: a840776d-bc1b-4a9d-859c-fc23192eda45
		summarizeBy: none
		sourceColumn: Quarter_

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Day Name EN'
		dataType: string
		lineageTag: 9aa50c8e-0f4a-4081-97f9-9c80e4f30a5f
		summarizeBy: none
		sourceColumn: Day Name EN
		sortByColumn: 'Day Number'

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: c3b7998a-5d50-4050-b95f-f15db34a5e81
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Legal Holiday'
		dataType: string
		lineageTag: fcc8b33d-2890-4dab-b29b-f07370ee785d
		summarizeBy: none
		sourceColumn: Legal Holiday

		annotation SummarizationSetBy = Automatic

	column 'Work Day'
		dataType: string
		lineageTag: 89b604b3-1313-4226-984e-fef0333cd6c9
		summarizeBy: none
		sourceColumn: Work Day

		annotation SummarizationSetBy = Automatic

	column 'Week Number ISO'
		dataType: int64
		lineageTag: a4122ef7-3c31-4489-92c1-13907e4bd259
		summarizeBy: none
		sourceColumn: Week Number ISO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month Year' = ```
			FORMAT([Date Range],"mmm-yyyy") 
			```
		lineageTag: 8c65e76a-2954-40f3-a76f-a0bdd15b8c92
		summarizeBy: none
		sortByColumn: 'Month Year sort'

		annotation SummarizationSetBy = Automatic

	column 'Month Year sort' = FORMAT([Date Range],"yyyymm")
		lineageTag: cd3087d4-f701-410c-960c-d94801b3407e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Week sort' = DIM_CALENDAR_FUTUR[Month Year sort]& DIM_CALENDAR_FUTUR[Week Number ISO]
		lineageTag: 080c30fd-b9eb-413f-87d2-d87d3b0dc6f3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsInRanges = IF('DIM_CALENDAR_FUTUR'[Date YYYYMMDD] <= [Max Date Past] ,TRUE(), FALSE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fa22b8c1-f266-4ed8-95b7-9c2ba1b2c45a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Covid = IF(DIM_CALENDAR_FUTUR[Month Year] = "mars-2020", "COVID",BLANK())
		lineageTag: fda9c182-4b61-4d14-ad99-f44d55e7b625
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Info' = CONCATENATE(CONCATENATE(DIM_CALENDAR_FUTUR[Month Year], "   " ),DIM_CALENDAR_FUTUR[Covid])
		lineageTag: 7b9300ad-76b1-40f7-87da-97c4e114f4c8
		summarizeBy: none
		sortByColumn: 'Month Year sort'

		annotation SummarizationSetBy = Automatic

	column WEEK_NUMBER_YYYYWWW_ISO
		dataType: string
		lineageTag: 8bcce2e4-0c0c-49dc-a8e7-55b4b7b50994
		summarizeBy: none
		sourceColumn: WEEK_NUMBER_YYYYWWW_ISO

		annotation SummarizationSetBy = Automatic

	column ADAPTED_SERVICE_HOLIDAY
		dataType: string
		lineageTag: 4f3409a5-172a-4db7-a6ab-dc8815a352c6
		summarizeBy: none
		sourceColumn: ADAPTED_SERVICE_HOLIDAY

		annotation SummarizationSetBy = Automatic

	column 'Day Name First  EN'
		dataType: string
		lineageTag: ea7b4aef-3db5-4796-93e2-698082f7650a
		summarizeBy: none
		sourceColumn: Day Name First  EN
		sortByColumn: 'Day Number'

		annotation SummarizationSetBy = Automatic

	column 'Year - value'
		dataType: string
		lineageTag: c0167e78-19ef-4e3e-843e-843fdcf446f6
		summarizeBy: none
		sourceColumn: Year - value

		annotation SummarizationSetBy = Automatic

	column WEEK_DATE
		dataType: string
		lineageTag: 8c72d053-7c6e-4b18-8535-ba306b14ad71
		summarizeBy: none
		sourceColumn: WEEK_DATE
		sortByColumn: WEEK_NUMBER_YYYYWWW_ISO

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WEEKEND_EOY
		dataType: string
		lineageTag: 36e81612-785a-43ee-b960-b091a09e1b07
		summarizeBy: none
		sourceColumn: WEEKEND_EOY

		annotation SummarizationSetBy = Automatic

	hierarchy 'Year Hierarchy - INFO'
		lineageTag: 73a9029c-7b72-4efc-a577-5020e2cd559b

		level Year
			lineageTag: 786cbc6c-ff3a-4330-a5dc-f4615852b41a
			column: Year

		level 'Month Info'
			lineageTag: f9ef2e7f-ba3a-4e54-968f-93381239e951
			column: 'Month Info'

	hierarchy Hierarchy
		lineageTag: 2bc169ca-b2a9-47d5-bc50-416671c2e60a

		level Year
			lineageTag: 6e032f2d-6afa-421b-aa9d-5daf15e91c02
			column: Year

		level Quarter
			lineageTag: ee3e11a4-bad9-481c-9571-9298f8bc2b03
			column: Quarter

		level Month_
			lineageTag: a50a0020-3503-427f-88d6-8cad8360be7d
			column: Month_

		level Week
			lineageTag: e06f95ec-2890-4647-88a7-cf032ba1a699
			column: Week

		level 'Date Range'
			lineageTag: 1a33263b-9ee7-465f-b409-b0f3a560e769
			column: 'Date Range'

	partition DIM_CALENDAR_FUTUR-7dcf9b38-ccc5-42fc-bc4b-ed7c205591c9 = m
		mode: import
		queryGroup: 'Forecast Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_ONCE, [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    V_PBI_DIM_CALENDAR1 = PBI_VLT341{[Name="DISTRIPOST_DIM_CALENDAR_FUTUR"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(V_PBI_DIM_CALENDAR1,{{"Week Number ISO", Int64.Type}, {"Quarter_", Int64.Type}, {"Month", Int64.Type}, {"Day", Int64.Type}, {"Month Number", Int64.Type}, {"Date YYYYMMDD", Int64.Type}, {"Day Number", Int64.Type}, {"Year", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Date YYYYMMDD] > 20210101),
				    #"Inserted First Characters" = Table.AddColumn(#"Filtered Rows", "Day Name First  EN", each Text.Start([Day Name EN], 2), type text),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted First Characters",{"PIC_KEY", "Day Name", "Date tooltip", "Date YYYYMMDD", "Day Number", "Year", "Month Number", "Day", "Month", "Quarter_", "Day Name EN", "Date Range", "Month Name", "Legal Holiday", "Work Day", "Week Number ISO", "WEEK_NUMBER_YYYYWWW_ISO", "ADAPTED_SERVICE_HOLIDAY", "Day Name First  EN"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Reordered Columns", "Year", "Year - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Year - Copy", "Year - value"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Year - value", type text}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type1", each [Date YYYYMMDD] >= 20230101)
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

