table DIM_REORG_VLT
	lineageTag: 4e5e41fb-ef98-4f94-8e6e-7c718cdb9ea1

	measure 100% = 1
		formatString: 0
		lineageTag: 19ba5a00-0d66-4e45-972c-340053238a7d

	column MASTER_REORG_ID
		dataType: double
		lineageTag: 61b9fd44-1169-4291-b390-2310f5a62880
		summarizeBy: none
		sourceColumn: MASTER_REORG_ID

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POSTAL_CODE
		dataType: int64
		formatString: 0
		lineageTag: 3ccb9123-bd06-450a-ae76-6f59e941418e
		summarizeBy: none
		sourceColumn: POSTAL_CODE

		annotation SummarizationSetBy = Automatic

	column REGIO_NAME
		dataType: string
		lineageTag: 8833f04d-52e6-4a5f-88b7-69e8f874f950
		summarizeBy: none
		sourceColumn: REGIO_NAME

		annotation SummarizationSetBy = Automatic

	column DC_NAME
		dataType: string
		lineageTag: f6dc4798-a180-4b98-b79f-142f5564f841
		summarizeBy: none
		sourceColumn: DC_NAME

		annotation SummarizationSetBy = Automatic

	column MC_NAME
		dataType: string
		lineageTag: 71277fbc-ec9b-46d9-911d-58b8c441bf77
		summarizeBy: none
		sourceColumn: MC_NAME

		annotation SummarizationSetBy = Automatic

	column DM_NAME
		dataType: string
		lineageTag: d52f0236-51bf-48b6-8ed8-9011bb3a39ab
		summarizeBy: none
		sourceColumn: DM_NAME

		annotation SummarizationSetBy = Automatic

	column REORG_START_DATE_YYYYMMDD
		dataType: double
		lineageTag: 808dd256-e983-4e24-81d4-7e7b243d5e90
		summarizeBy: sum
		sourceColumn: REORG_START_DATE_YYYYMMDD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REORG_END_DATE_YYYYMMDD
		dataType: double
		lineageTag: 13e5d348-608e-4cf1-95f3-2c3d26025b3f
		summarizeBy: sum
		sourceColumn: REORG_END_DATE_YYYYMMDD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MSTR_REORG_START_DATE_YYYYMMDD
		dataType: double
		lineageTag: 69b44490-8001-4b55-9eb4-ad81c6173ae2
		summarizeBy: sum
		sourceColumn: MSTR_REORG_START_DATE_YYYYMMDD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RANK_REORG
		dataType: int64
		formatString: 0
		lineageTag: 8b1211c9-f45d-4ae6-975a-3d6a45a6bcb6
		summarizeBy: none
		sourceColumn: RANK_REORG

		changedProperty = DataType

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'REORG START dateFormatted' = Date(Left([REORG_START_DATE_YYYYMMDD],4),Right(left([REORG_START_DATE_YYYYMMDD],6),2),right([REORG_START_DATE_YYYYMMDD],2))
		formatString: dd/mm/yyyy
		lineageTag: 2587206b-5ab5-419a-aabd-1a7d3ecae648
		summarizeBy: none

		variation Variation
			isDefault
			relationship: c85dc122-6337-44b9-9bc0-fe749966e373
			defaultHierarchy: LocalDateTable_f3083b54-4a1e-4886-a78c-b96c3205a433.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'REORG END dateFormatted' = Date(Left([REORG_END_DATE_YYYYMMDD],4),Right(left([REORG_END_DATE_YYYYMMDD],6),2),right([REORG_END_DATE_YYYYMMDD],2))
		formatString: dd/mm/yyyy
		lineageTag: 7c56501c-f726-4125-a4f8-ca8d2da9084b
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e7b42fee-cb1f-4198-8e89-023592a4a641
			defaultHierarchy: LocalDateTable_4a96697f-8ab9-4323-86f0-c8957c2db8ac.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column REORG_ID
		dataType: double
		lineageTag: 545eac8b-dd2d-488f-9aa1-920d6e667a79
		summarizeBy: count
		sourceColumn: REORG_ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POSTAL_CODE_SEARCH
		dataType: string
		lineageTag: e61aaf5a-869a-4054-bea5-cdf11218acd0
		summarizeBy: none
		sourceColumn: POSTAL_CODE_SEARCH

		annotation SummarizationSetBy = Automatic

	column KEY_REOG_ORG
		dataType: string
		lineageTag: 320c3bd7-3729-4c48-acc0-3f25b09e8f21
		summarizeBy: none
		sourceColumn: KEY_REOG_ORG

		annotation SummarizationSetBy = Automatic

	column IS_LAST_MASTER_REORG
		dataType: string
		lineageTag: a33b55c3-0230-4a6e-8201-32d8ab3e0f31
		summarizeBy: none
		sourceColumn: IS_LAST_MASTER_REORG

		annotation SummarizationSetBy = Automatic

	partition DIM_REORG_VLT-b05846e7-3cf3-4d16-b1c8-17f1f867535c = m
		mode: import
		queryGroup: 'DIM Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_SECOND, [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    V_PBI_DIM_REORG_VLT1 = PBI_VLT341{[Name="DISTRIPOST_DIM_REORGANIZATION"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(V_PBI_DIM_REORG_VLT1, {"POSTAL_CODE"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Duplicates","AWANS MC","VISE MC",Replacer.ReplaceText,{"MC_NAME"}),
				    #"Protected Key" = Table.SelectRows(#"Replaced Value", each [REORG_ID] <> null and [REORG_ID] <> ""),
				    #"Changed Type" = Table.TransformColumnTypes(#"Protected Key",{{"POSTAL_CODE", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "POSTAL_CODE", "POSTAL_CODE_SEARCH"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"POSTAL_CODE_SEARCH", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

