table DISTRIPOST_TBL_IRN_PLANNED
	lineageTag: 7ddefea2-62c1-4916-9894-2e850d8efcb0

	measure '# Forecast Order' = CALCULATE(DISTINCTCOUNT(DISTRIPOST_TBL_IRN_PLANNED[ORDER_REFERENCE]), DISTRIPOST_TBL_IRN_PLANNED[CUSTOMER_NAME] <>"ORG")
		formatString: 0
		lineageTag: 14eaaf35-5e5e-4463-9e1f-cced6a521c16

	column CUSTOMER_NAME
		dataType: string
		lineageTag: de2288a7-14d8-4357-8344-0d9aa644439c
		summarizeBy: none
		sourceColumn: CUSTOMER_NAME

		annotation SummarizationSetBy = Automatic

	column TITLE_OF_ITEM
		dataType: string
		lineageTag: 1c5ed1b5-cddf-4c2a-9bae-23dd37342529
		summarizeBy: none
		sourceColumn: TITLE_OF_ITEM

		annotation SummarizationSetBy = Automatic

	column IS_STANDARD
		dataType: string
		lineageTag: 73279c8b-391b-4adb-b762-c6226e834bc3
		summarizeBy: none
		sourceColumn: IS_STANDARD

		annotation SummarizationSetBy = Automatic

	column STATUS
		dataType: string
		lineageTag: 733e6d88-f5de-4cdd-ab2e-c1569300717b
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column REQ_DISTR_START_DATE_YYYYMMDD
		dataType: int64
		lineageTag: a04c66ae-1fdf-4710-96d4-ac376254c93b
		summarizeBy: none
		sourceColumn: REQ_DISTR_START_DATE_YYYYMMDD

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REQ_DISTR_END_DATE_YYYYMMDD
		dataType: double
		lineageTag: b5934f61-3bfa-44d4-b649-723fb564eb56
		summarizeBy: none
		sourceColumn: REQ_DISTR_END_DATE_YYYYMMDD

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ROUND_NAME
		dataType: string
		lineageTag: 7960faac-801b-4815-be2b-dcd616a1db82
		summarizeBy: none
		sourceColumn: ROUND_NAME

		annotation SummarizationSetBy = Automatic

	column DISTRIBUTION_ORDER
		dataType: string
		lineageTag: a343dd2b-954e-4315-a8ee-205d9761d309
		summarizeBy: none
		sourceColumn: DISTRIBUTION_ORDER

		annotation SummarizationSetBy = Automatic

	column TOTAL_ZZA_SIDE_A
		dataType: int64
		formatString: 0
		lineageTag: 75be337c-53a2-4c9e-a119-4f3f081e19cb
		summarizeBy: none
		sourceColumn: TOTAL_ZZA_SIDE_A

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column TOTAL_ZZA_SIDE_B
		dataType: double
		formatString: 0
		lineageTag: 3ccf3f0b-ed47-482e-bc54-f83d7ca7aaf8
		summarizeBy: none
		sourceColumn: TOTAL_ZZA_SIDE_B

		annotation SummarizationSetBy = User

	column 'Distribution Begin Date' = ```
			
			DATE(
			    LEFT([REQ_DISTR_START_DATE_YYYYMMDD], 4), 
			    MID([REQ_DISTR_START_DATE_YYYYMMDD], 5, 2), 
			    RIGHT([REQ_DISTR_START_DATE_YYYYMMDD], 2)
			)
			
			```
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9d525d5b-f880-45ad-a7cd-494439aba034
		summarizeBy: none

		variation Variation
			isDefault
			relationship: ec05815b-4b72-45c0-ac1d-b050c20dec3e
			defaultHierarchy: LocalDateTable_d96bcc60-9808-41e3-a461-fe38b72bf566.'Hiérarchie de dates'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ORG_ENA
		dataType: double
		formatString: #,0
		lineageTag: 5755b203-1b9a-4999-b8e2-3d430e0821e9
		summarizeBy: sum
		sourceColumn: ORG_ENA

		annotation SummarizationSetBy = Automatic

	column WEEK_DATE
		dataType: string
		lineageTag: 86b82c02-85af-4c69-99ae-66125bcec9cb
		summarizeBy: none
		sourceColumn: WEEK_DATE

		annotation SummarizationSetBy = Automatic

	column X = "X"
		lineageTag: dac19f3b-4478-46d2-8e78-9a2a092413ec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PRS_ID
		dataType: string
		lineageTag: f4d51e47-eee7-456a-9a3a-e0a2005defc5
		summarizeBy: none
		sourceColumn: PRS_ID

		annotation SummarizationSetBy = Automatic

	column KEY_DISTRIPOST
		dataType: string
		lineageTag: 894c99c5-1f79-4652-8dc2-f99d25c5537b
		summarizeBy: none
		sourceColumn: KEY_DISTRIPOST

		annotation SummarizationSetBy = Automatic

	column SLOT_ELECTION_FLAG
		dataType: string
		lineageTag: 6a8e3776-bcb0-43c3-8dbf-c0187be62b32
		summarizeBy: none
		sourceColumn: SLOT_ELECTION_FLAG

		annotation SummarizationSetBy = Automatic

	column POSTAL_CODE
		dataType: double
		lineageTag: 747654f5-5a9d-4307-a116-ed871c285caf
		summarizeBy: sum
		sourceColumn: POSTAL_CODE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ORDER_REFERENCE
		dataType: string
		lineageTag: 5564f2a4-ecf2-407b-bb28-0a1f11a3a48c
		summarizeBy: none
		sourceColumn: ORDER_REFERENCE

		annotation SummarizationSetBy = Automatic

	column PRODUCT_CATEGORY_NAME
		dataType: string
		lineageTag: 433e0a38-6f18-474d-838b-89192280460e
		summarizeBy: none
		sourceColumn: PRODUCT_CATEGORY_NAME

		annotation SummarizationSetBy = Automatic

	column TOTAL_MAILBOX_VOLUME
		dataType: double
		formatString: #,0
		lineageTag: b8edfc4d-a537-4528-b670-30ab1cd28de8
		summarizeBy: sum
		sourceColumn: TOTAL_MAILBOX_VOLUME

		annotation SummarizationSetBy = Automatic

	column KEY_ORG
		dataType: string
		lineageTag: 22f0107e-6c84-4e11-9271-801e6e8d3520
		summarizeBy: none
		sourceColumn: KEY_ORG

		annotation SummarizationSetBy = Automatic

	partition DISTRIPOST_TBL_IRN_PLANNED = m
		mode: import
		queryGroup: 'Forecast Queries'
		source =
				let
				    Source = Oracle.Database(PBI_VLT341_ONCE, [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    DISTRIPOST_TBL_IRN_PLANNED1 = PBI_VLT341{[Name="DISTRIPOST_TBL_IRN_PLANNED"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(DISTRIPOST_TBL_IRN_PLANNED1, "SLOT_ELECTION_FLAG", each if [TITLE_OF_ITEM] = "Blokkeerorder elections EOW" then "Yes" else if [TITLE_OF_ITEM] = "Blokkeerorder elections BOW" then "Yes" else "No", type text),
				    #"Inserted Merged Column" = Table.AddColumn(#"Added Conditional Column", "KEY_ORG", each Text.Combine({[KEY_DISTRIPOST], "_", [ROUND_NAME]}), type text)
				in
				    #"Inserted Merged Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

