table DISTRIPOST_TBL_IRN_PLANNED_ORG
	lineageTag: 99fce657-05e0-4462-a8ad-4d7789f1ded0

	column ORG_ENA
		dataType: double
		formatString: #,0
		lineageTag: b5be5556-5569-439a-9f73-7bec6d2e2114
		summarizeBy: sum
		sourceColumn: ORG_ENA

		annotation SummarizationSetBy = Automatic

	column KEY_DISTRIPOST
		dataType: string
		lineageTag: 6406ba3e-1f76-42a3-b522-838be565a0a7
		summarizeBy: none
		sourceColumn: KEY_DISTRIPOST

		annotation SummarizationSetBy = Automatic

	column ROUND_NAME
		dataType: string
		lineageTag: 3c731c28-5e56-4619-9dce-594a7c184b20
		summarizeBy: none
		sourceColumn: ROUND_NAME

		annotation SummarizationSetBy = Automatic

	column KEY_ORG
		dataType: string
		lineageTag: 0cbaa4e7-f82f-4637-b026-b07d0224cf75
		summarizeBy: none
		sourceColumn: KEY_ORG

		annotation SummarizationSetBy = Automatic

	partition DISTRIPOST_TBL_IRN_PLANNED_ORG = m
		mode: import
		queryGroup: 'Forecast Queries'
		source =
				let
				    Source = DISTRIPOST_TBL_IRN_PLANNED,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ORG_ENA", "KEY_DISTRIPOST", "WEEK_DATE", "POSTAL_CODE", "ROUND_NAME"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Other Columns",{"WEEK_DATE", "POSTAL_CODE"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Removed Columns", "KEY_ORG", each Text.Combine({[KEY_DISTRIPOST], "_", [ROUND_NAME]}), type text)
				in
				    #"Inserted Merged Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

