table VLT_DIM_REORGANIZATION
	lineageTag: 9208c7e4-54d0-4427-aafe-e32814948c5d

	column KEY_REOG_ORG
		dataType: string
		lineageTag: 56b3fa00-8803-474b-b4fc-6cbd3974fbc6
		summarizeBy: none
		sourceColumn: KEY_REOG_ORG

		annotation SummarizationSetBy = Automatic

	column MASTER_REORG_ID
		dataType: int64
		formatString: 0
		lineageTag: 58d82fd4-bcd8-4dd5-94c1-6656ab1675e7
		summarizeBy: none
		sourceColumn: MASTER_REORG_ID

		annotation SummarizationSetBy = Automatic

	column IS_LAST_MASTER_REORG
		dataType: string
		lineageTag: 0f7b0ae4-e2b8-491e-b281-44355f2b76eb
		summarizeBy: none
		sourceColumn: IS_LAST_MASTER_REORG

		annotation SummarizationSetBy = Automatic

	column REORG_IN_PROGRESS
		dataType: string
		lineageTag: cb399353-3aaf-498a-945b-727a8a7b774a
		summarizeBy: none
		sourceColumn: REORG_IN_PROGRESS

		annotation SummarizationSetBy = Automatic

	column IS_LAST_REORG
		dataType: string
		lineageTag: eaf70b13-1a1b-4c09-a8bb-e8b06783c725
		summarizeBy: none
		sourceColumn: IS_LAST_REORG

		annotation SummarizationSetBy = Automatic

	column IS_PREV_MASTER_REORG
		dataType: string
		lineageTag: c43f41a0-25e5-48eb-b591-5daf567ca696
		summarizeBy: none
		sourceColumn: IS_PREV_MASTER_REORG

		annotation SummarizationSetBy = Automatic

	column IS_PREV_REORG
		dataType: string
		lineageTag: 94a1c4ac-7d66-42a5-815e-e6a0def8a51f
		summarizeBy: none
		sourceColumn: IS_PREV_REORG

		annotation SummarizationSetBy = Automatic

	column REORG_ID
		dataType: int64
		formatString: 0
		lineageTag: 2baa015c-3f22-4b10-b113-33d3617b71eb
		summarizeBy: none
		sourceColumn: REORG_ID

		annotation SummarizationSetBy = User

	column POSTAL_CODE
		dataType: string
		lineageTag: 33cbb6c2-ab26-4e11-b404-55d0b319d31b
		summarizeBy: none
		sourceColumn: POSTAL_CODE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column REGIO_NAME
		dataType: string
		lineageTag: 7d988e0b-b455-40f5-82ce-3e2944f0ee56
		summarizeBy: none
		sourceColumn: REGIO_NAME

		annotation SummarizationSetBy = Automatic

	column DC_NAME
		dataType: string
		lineageTag: f6f644f3-a6ea-44c5-a997-efe1404eb09c
		summarizeBy: none
		sourceColumn: DC_NAME

		annotation SummarizationSetBy = Automatic

	column MC_NAME
		dataType: string
		lineageTag: 95163460-24e9-4b35-a061-7cae418426dc
		summarizeBy: none
		sourceColumn: MC_NAME

		annotation SummarizationSetBy = Automatic

	column DM_NAME
		dataType: string
		lineageTag: 6561ed50-ffe8-4065-8766-2e476753be10
		summarizeBy: none
		sourceColumn: DM_NAME

		annotation SummarizationSetBy = Automatic

	column REORG_START_DATE_YYYYMMDD
		dataType: int64
		formatString: 0
		lineageTag: ec01707c-6f69-4dea-9bcb-4b41bcce2b3d
		summarizeBy: none
		sourceColumn: REORG_START_DATE_YYYYMMDD

		annotation SummarizationSetBy = Automatic

	column REORG_END_DATE_YYYYMMDD
		dataType: int64
		formatString: 0
		lineageTag: ef916201-626f-4469-9c62-76919311dcc1
		summarizeBy: none
		sourceColumn: REORG_END_DATE_YYYYMMDD

		annotation SummarizationSetBy = User

	column MSTR_REORG_START_DATE_YYYYMMDD
		dataType: int64
		formatString: 0
		lineageTag: a57879a0-4735-462f-ac86-46d629848550
		summarizeBy: none
		sourceColumn: MSTR_REORG_START_DATE_YYYYMMDD

		annotation SummarizationSetBy = User

	column RANK_REORG
		dataType: int64
		formatString: 0
		lineageTag: f09935ee-3e97-45c6-9c66-0b76d54da3ac
		summarizeBy: none
		sourceColumn: RANK_REORG

		annotation SummarizationSetBy = User

	column MSTER_REORG_START
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: f0a12dc2-5e78-48df-b71e-8074aa1f332f
		summarizeBy: none
		sourceColumn: MSTER_REORG_START

		variation Variation
			isDefault
			relationship: 9da9c22d-fb3f-44fc-98ab-be3e438526ae
			defaultHierarchy: LocalDateTable_7cf769a3-dbb1-43bd-8662-3a4578093824.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column REORG_START
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b105cab-c874-40e5-9b08-670d6861814a
		summarizeBy: none
		sourceColumn: REORG_START

		variation Variation
			isDefault
			relationship: 6c4c39b8-0ddf-4425-8439-3237cca0a1fd
			defaultHierarchy: LocalDateTable_85bc92de-a172-4f2d-9843-ccc9d8f57ac3.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column REORG_END
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 4e95a2f9-0efa-4053-a874-ecfcfa218892
		summarizeBy: none
		sourceColumn: REORG_END

		variation Variation
			isDefault
			relationship: 22645424-f924-4f60-9a2a-c5acb20e6c00
			defaultHierarchy: LocalDateTable_e2d50599-d05e-499d-acd4-9a360eeffcd3.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition VLT_DIM_REORGANIZATION = m
		mode: import
		source =
				let
				    Source = Oracle.Database("MM8P1", [HierarchicalNavigation=true]),
				    PBI_VLT341 = Source{[Schema="PBI_VLT341"]}[Data],
				    VLT_DIM_REORGANIZATION1 = PBI_VLT341{[Name="VLT_DIM_REORGANIZATION"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(VLT_DIM_REORGANIZATION1,{{"MASTER_REORG_ID", Int64.Type}, {"REORG_ID", Int64.Type}, {"POSTAL_CODE", Int64.Type}, {"REORG_START_DATE_YYYYMMDD", Int64.Type}, {"REORG_END_DATE_YYYYMMDD", Int64.Type}, {"MSTR_REORG_START_DATE_YYYYMMDD", Int64.Type}, {"RANK_REORG", Int64.Type}}),
				    #"Date insérée" = Table.AddColumn(#"Type modifié", "Date", each Date.From(Text.From([MSTR_REORG_START_DATE_YYYYMMDD], "fr-BE")), type date),
				    #"Colonnes renommées" = Table.RenameColumns(#"Date insérée",{{"Date", "MSTER_REORG_START"}}),
				    #"Date insérée1" = Table.AddColumn(#"Colonnes renommées", "Date", each Date.From(Text.From([REORG_START_DATE_YYYYMMDD], "fr-BE")), type date),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Date insérée1",{{"Date", "REORG_START"}}),
				    #"Date insérée2" = Table.AddColumn(#"Colonnes renommées1", "Date", each Date.From(Text.From([REORG_END_DATE_YYYYMMDD], "fr-BE")), type date),
				    #"Colonnes renommées2" = Table.RenameColumns(#"Date insérée2",{{"Date", "REORG_END"}})
				in
				    #"Colonnes renommées2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

